# Generated by Django 5.1 on 2024-08-28 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=200)),
                ('post_description', models.CharField(max_length=200)),
                ('post_date', models.DateTimeField(auto_now_add=True)),
                ('post_author', models.CharField(max_length=200)),
                ('post_body', models.TextField()),
            ],
        ),
    ]
